INSERT INTO rezsched_baserotations (rotationCode, rotationDescr) VALUES ('ORI','Orientation');
INSERT INTO rezsched_baserotations (rotationCode, rotationDescr) VALUES ('NF-1','Night Float');
INSERT INTO rezsched_baserotations (rotationCode, rotationDescr) VALUES ('PED-IP','Pediatrics - Inpatient');
INSERT INTO rezsched_baserotations (rotationCode, rotationDescr) VALUES ('OB','Obstetrics');
INSERT INTO rezsched_baserotations (rotationCode, rotationDescr) VALUES ('Card-IP','Cardiology - Inpatient');
INSERT INTO rezsched_baserotations (rotationCode, rotationDescr) VALUES ('ENDO','Endocrinology');
INSERT INTO rezsched_baserotations (rotationCode, rotationDescr) VALUES ('NEPH','Nephrology');
INSERT INTO rezsched_baserotations (rotationCode, rotationDescr) VALUES ('ENT','Ear, Nose, Throat');
INSERT INTO rezsched_baserotations (rotationCode, rotationDescr) VALUES ('OPH','Ophthalmology');
INSERT INTO rezsched_baserotations (rotationCode, rotationDescr) VALUES ('ORTHO','Orthopedics');
INSERT INTO rezsched_baserotations (rotationCode, rotationDescr) VALUES ('ICU','Intensive Care Unit');
INSERT INTO rezsched_baserotations (rotationCode, rotationDescr) VALUES ('PEDS-OP','Pediatrics Outpatient');
INSERT INTO rezsched_baserotations (rotationCode, rotationDescr) VALUES ('DEVPEDS','Developmental Pediatrics');
INSERT INTO rezsched_baserotations (rotationCode, rotationDescr) VALUES ('GYN','Gynecology');
INSERT INTO rezsched_baserotations (rotationCode, rotationDescr) VALUES ('PSYCH','Psychiatry');
INSERT INTO rezsched_baserotations (rotationCode, rotationDescr) VALUES ('NBN','Newborn Nursery');
INSERT INTO rezsched_baserotations (rotationCode, rotationDescr) VALUES ('ER','Emergency Medicine');
INSERT INTO rezsched_baserotations (rotationCode, rotationDescr) VALUES ('Card-OP','Cardiology Outpatient');
INSERT INTO rezsched_baserotations (rotationCode, rotationDescr) VALUES ('DERM','Dermatology');
INSERT INTO rezsched_baserotations (rotationCode, rotationDescr) VALUES ('SPTMED','Sports Medicine');
INSERT INTO rezsched_baserotations (rotationCode, rotationDescr) VALUES ('URO','Urology');
INSERT INTO rezsched_baserotations (rotationCode, rotationDescr) VALUES ('NEURO','Neurology');
INSERT INTO rezsched_baserotations (rotationCode, rotationDescr) VALUES ('NF-2','Night Float');
INSERT INTO rezsched_baserotations (rotationCode, rotationDescr) VALUES ('NF-3','Night Float');